### PR TITLE
Full Allies Expansions images included

### PR DESCRIPTION
**Pull request by gillesgros**
Hello,
Full allies set with images, process script updated.
New card type Ally introduced

### CODE REVIEW

**Comment by blakevanlan** [comment]
Thank you! I'll integrate this into the branch I have with support for Ally cards and get it merged.

**Comment by gillesgros** [comment]
Be advice,  it is not yet working.
No link between ally and favor.
I am workinf on it

**Comment by blakevanlan** [comment]
@gillesgros Got it. I'm actually giving it a shot too on the `allies` branch.

**Comment by blakevanlan** [comment]
Added with #111

**Pull request closed without merging**
