### PR TITLE
Plunder

### PR DESCRIPTION
**Pull request by markbrockettrobson**
WIP , traits are not selected by the randomizer, IDK why yet will look again tomorrow

### CODE REVIEW

**Comment by gillesgros** [comment]
in cards.ts
```
  static getAllTraits(cards: Card[]): Trait[] {
    return Cards.getCardsOfType<Ally>(cards, Trait);
  }
```
should be 
```
  static getAllTraits(cards: Card[]): Trait[] {
    return Cards.getCardsOfType<Trait>(cards, Trait);
  }
```

**Comment by markbrockettrobson** [comment]
OK ready to Review @gillesgros 

Thanks in advance

**Comment by gillesgros** [comment]
On the randomizer page, when Traits are selected the title remains "Events" or "Events & Ways" it should be more specific

On the recommended kingdoms page, on a set when Trait and Event are selected display is ok, when just trait it is not so fine.

**Comment by gillesgros** [comment]
When reloading page on recommended kigndoms, it switch back to Dominion 1st Ed. 
May be is was the same before. I need to check.
it aslo looks like there is a refresh depending on langy=uage (not so sure)

**Comment by markbrockettrobson** [comment]
> 

I think we can leave that for an issue

**Comment by markbrockettrobson** [comment]
> On the randomizer page, when Traits are selected the title remains "Events" or "Events & Ways" it should be more specific
> On the recommended kingdoms page, on a set when Trait and Event are selected display is ok, when just trait it is not so fine.

on it now

**Comment by gillesgros** [comment]
Hello, 
do you need help to publish your work ?

**Comment by markbrockettrobson** [comment]
Sorry just finding time has been hard feel free to push it over the line

**Comment by gillesgros** [comment]
Sound good to me

**Comment by gillesgros** [comment]
You need to deploy it.
Tell me if you need me to do it

**Comment by markbrockettrobson** [comment]
just rand the cicd deployment on the latest master 
https://github.com/blakevanlan/KingdomCreator/actions/runs/4107968607

no luck, how do you deploy this project ?

**Comment by gillesgros** [comment]
You need to buy the project. push it on git and then run the CICD framework

**Pull request merged**
