### PR TITLE
Hunterlands2

### PR DESCRIPTION
**Pull request by markbrockettrobson**

### CODE REVIEW

**Comment by markbrockettrobson** [comment]
Like 
https://github.com/blakevanlan/KingdomCreator/pull/115
https://github.com/blakevanlan/KingdomCreator/pull/114

we dont have a full list of non English names yet http://wiki.dominionstrategy.com/index.php/List_of_cards_in_other_languages

**Comment by markbrockettrobson** [comment]
@blakevanlan  let me know if you want me to add anything else.

**Comment by blakevanlan** [comment]
Thanks for the submission @markbrockettrobson ! Hope to get these merged and deployed within the next week

**Comment by markbrockettrobson** [comment]
any update @blakevanlan ?

**Comment by blakevanlan** [comment]
@markbrockettrobson Apologies for never getting back to you. I'm swamped and can't keep up here! I've added @gillesgros and you as contributors so you can get this changed merged and maintained :)

**Comment by gillesgros** [comment]
I will try to do my best on that.
Wish you all the best for the new year.

Gilles

**Comment by markbrockettrobson** [comment]
Thanks I will try get to plunder next week

**Comment by gillesgros** [comment]
@markbrockettrobson <https://github.com/markbrockettrobson>, we need to
sync on who does what ?

If you go for plunder, I go for the 2nd edition extension.
Tell me if it works for you.

Regards,

Gilles

**Comment by markbrockettrobson** [comment]
@gillesgros 

Sounds good can you please review

https://github.com/blakevanlan/KingdomCreator/pull/114
https://github.com/blakevanlan/KingdomCreator/pull/115
https://github.com/blakevanlan/KingdomCreator/pull/116

**Pull request closed without merging**
