### PR TITLE
PR Merging multiple changes + translation

### PR DESCRIPTION
**Pull request by gillesgros**
PR # 136 - Polish language support
+ PR # 141 - added German translation for RandomizerSidebar 
+ PR # 147 -  fix encoding errors
+ I #51 - Query parameters aren't cleaned up
+ I #128 - Bane card present without Young Witch in the kingdom
+ I # 67 - Landmarks aren't generated if the query parameters have supply cards

### CODE REVIEW

**Comment by gillesgros** [comment]
If you have no time, let me know.

**Comment by markbrockettrobson** [comment]
Sorry time has been hard to find

**Comment by markbrockettrobson** [comment]
sorry time has been hard to , I will try this weekend but ping me if I dont get back to you by Monday

**Comment by gillesgros** [comment]
Any time to look into it ?
or should I move forward ?

**Comment by markbrockettrobson** [comment]
ya sorry cant find the time , just move forward sorry

**Comment by gillesgros** [comment]
Adding features and translations.
Need to migrate ti vue 3 and vite.js ?

**Comment by gillesgros** [comment]
Hello 9tmark,

I am on the migration path to vue 3 and vite (see my repos). Vue 3 seems OK, but still struggling with vite and its subtleties.

**Pull request merged**
