### PR TITLE
Bane, rulebooks, and more sets

### PR DESCRIPTION
**Pull request by blakevanlan**
Integrating #19

Shout out to @gillesgros for all the hardwork!

Changes
* Adds bane card to randomizer and recommended kingdoms
* Makes the rulebook page pretty
* Adds recommended kingdoms for second edition sets (baseset and Intrigue)
* [Bug] Fixes prioritize set to only have selected kingdoms

### CODE REVIEW

**Comment by gillesgros** [comment]
Hello,

Great that you cleanup some of my mess
I have to  confess, I started playing around with vue.js when deciding to
try to add a label on the card in set view to more easyt pick them.

I tested your bane card selection. I think some piece are broken.
The ability to "specify" a replacement card is not working anymore.
And when hitting randomize multiple time in a row (with cornucopia
selected) some times, the young witch is selected but with no bane card.

I am sure you should be more efficient to fix it than me.

Regards,
Gilles

**Comment by blakevanlan** [comment]
Oh you're right. I broke the specifying a card. I thought I was removing an old flow that allowed you to pick from a few replacement suggestions but really i removed the whole replacement dialog 🤦‍♂ 

> And when hitting randomize multiple time in a row (with cornucopia
selected) some times, the young witch is selected but with no bane card.

With only Cornucopia selected, there are only 3 possible bane cards and if those three cards are already part of the kingdom then there are no valid bane cards remaining. I chose not to implement the fix at the moment because it's fairly complete and it's ultimately very unlikely that someone really want to randomize Cornucopia by itself (there's only 13 cards in the set).

**Comment by gillesgros** [comment]
Hello,

Ok, the specify is now OK.
You still have a problem I stumble into.
The selected set are (dark age and cornucopia)

You  have a  set of kingdol with the young witch and a bane card selected.
Select on other card choose thru specify to randimize it. The bane card is
also randomized.

**Comment by blakevanlan** [comment]
Make sense. Missed updating that code path for bane. Should be fixed now.

There's a bug where selecting multiple cards then specifying replaces both too but haven't gotten around to fixing it.

**Pull request merged**
